name: 'Upload private package to pub.mpflutter.com'
description: 'Upload private package to pub.mpflutter.com'
branding:
  icon: 'upload-cloud'
  color: 'blue'
inputs:
  secret_id:
    description: 'Tencent cloud secret id. Should be referred to a encrypted environment variable'
    required: true
  secret_key:
    description: 'Tencent cloud secret key. Should be referred to a encrypted environment variable'
    required: true
  cos_bucket:
    description: 'COS bucket name'
    required: true
  cos_region:
    description: 'COS bucket region'
    required: true
  package_name:
    description: 'The package name.'
    required: true
  package_path:
    description: 'The source files location'
    required: true
runs:
  using: 'node16'
  main: 'index.js'
